config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  ActiveAdmin.routes(self)
  get 'about' => 'welcome#about'
  get 'policies' => 'welcome#policies'
  get 'insurance' => 'welcome#insurance'
  get 'services' => 'welcome#services'
  get 'contact' => 'welcome#contact'
  get 'resources' => 'welcome#resources'

  root to:'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable, :invite_for => 2.weeks


 def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "Unauthorized Access!"
      redirect_to root_path
    end
  end

 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def policies
  end

  def insurance
  end

  def services
  end

  def contact
  end

  def resources
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="navbar-fixed-bottom">
  <div class="text-center">
    <small> 
      <%= link_to "About", about_path %>
      | Anitha Palanisamy © 2015 
    </small>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top ">
  <div class="container-fluid head-style"> 
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-header-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand" >  
        <%= link_to "ConnectDoc", root_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="bs-header-navbar-collapse-1">
      <ul class="nav navbar-nav" >
          <li class="nav-hover"><%= link_to "Home", root_path %></li>
          <li class="nav-hover"><%= link_to "About", about_path %></li>
          <li class="nav-hover"><%= link_to "Services", services_path %></li>
          <li class="nav-hover"><%= link_to "Insurance", insurance_path %></li>
          <li class="nav-hover"><%= link_to "Office Policies", policies_path %></li>
          <li class="nav-hover"><%= link_to "Resources", resources_path %></li>
          <li class="nav-hover"><%= link_to "Contact Us", contact_path %></li>
          <li class="nav-hover"><%= link_to "Patients", '#' %></li>
      </ul>

      <div class="user-info navbar-right">
        <ul>
          <% if current_user %>
            Hello <%= link_to (current_user.email) %>!
            <%= link_to edit_user_registration_path, class: 'btn btn-info btn-sm' do %>
            <span class= "glyphicon glyphicon-user"></span>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-sm' do %>
            <span class="glyphicon glyphicon-log-out" ></span>
            <% end %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: 'sign btn btn-success btn-sm' %>
            <%= link_to "Sign up", new_user_registration_path, class: 'sign btn btn-success btn-sm' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectDoc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'layouts/navbar' %>
   <div class="header-spacer"></div>
   <div class="container body-content">
    <div class="row flash-msg">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="row col-md-12 other-content">
        <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 foot-size">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/insurance.html.erb
<h1>Welcome#insurance</h1>
<p>Find me in app/views/welcome/insurance.html.erb</p>

app/views/welcome/policies.html.erb
<h1>Welcome#policies</h1>
<p>Find me in app/views/welcome/policies.html.erb</p>

app/views/welcome/services.html.erb
<h1>Welcome#services</h1>
<p>Find me in app/views/welcome/services.html.erb</p>